In [1]:
import pandas as pd

melbourne_file_path = 'melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
melbourne_data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [2]:
melbourne_data = melbourne_data.dropna(axis = 0)

In [3]:
# The Prediction target
y = melbourne_data.Price

In [4]:
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']

In [5]:
# features models
X = melbourne_data[melbourne_features]

In [6]:
X.describe()

Rooms     Bathroom      Landsize    Lattitude   Longtitude
count  6196.000000  6196.000000   6196.000000  6196.000000  6196.000000
mean      2.931407     1.576340    471.006940   -37.807904   144.990201
std       0.971079     0.711362    897.449881     0.075850     0.099165
min       1.000000     1.000000      0.000000   -38.164920   144.542370
25%       2.000000     1.000000    152.000000   -37.855438   144.926198
50%       3.000000     1.000000    373.000000   -37.802250   144.995800
75%       4.000000     2.000000    628.000000   -37.758200   145.052700
max       8.000000     8.000000  37000.000000   -37.457090   145.526350

In [7]:
X.head()

Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954

In [8]:
from sklearn.tree import DecisionTreeRegressor

In [9]:
melbourne_model = DecisionTreeRegressor(random_state = 1)

In [10]:
melbourne_model.fit(X,y)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [11]:
print("Making predictions for the following 5 houses:")
print(X.head())
print("The predictions are")
print(melbourne_model.predict(X.head()))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
1      2       1.0     156.0   -37.8079    144.9934
2      3       2.0     134.0   -37.8093    144.9944
4      4       1.0     120.0   -37.8072    144.9941
6      3       2.0     245.0   -37.8024    144.9993
7      2       1.0     256.0   -37.8060    144.9954
The predictions are
[1035000. 1465000. 1600000. 1876000. 1636000.]


In [12]:
testing_data = pd.DataFrame({'Rooms':[2,3,4,5,8] , 'Bathroom':[1,2,1,3,4], 'Landsize':[156,124,201,300,405],'Lattitude':[-37.8079,-37.8089,-37.8000,-37.8100,-37.8008],'Longtitude':[144.9954,144.9994,144.9934,144.9940,144.9904]})

In [13]:
testing_data

Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2         1       156   -37.8079    144.9954
1      3         2       124   -37.8089    144.9994
2      4         1       201   -37.8000    144.9934
3      5         3       300   -37.8100    144.9940
4      8         4       405   -37.8008    144.9904

In [14]:
print("Making predictions for the following 5 houses:")
print(testing_data)
print("The predictions are")
print(melbourne_model.predict(testing_data))

Making predictions for the following 5 houses:
   Rooms  Bathroom  Landsize  Lattitude  Longtitude
0      2         1       156   -37.8079    144.9954
1      3         2       124   -37.8089    144.9994
2      4         1       201   -37.8000    144.9934
3      5         3       300   -37.8100    144.9940
4      8         4       405   -37.8008    144.9904
The predictions are
[1035000. 1200000. 1785000. 1212500. 5600000.]


In [15]:
from sklearn.metrics import mean_absolute_error

predicted_home_price = melbourne_model.predict(X)
mean_absolute_error(y , predicted_home_price)

1115.7467183128902

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
train_X,val_X,train_y,val_y = train_test_split(X,y,random_state = 0)

In [18]:
melbourne_model = DecisionTreeRegressor()
melbourne_model = melbourne_model.fit(train_X,train_y)

In [19]:
val_predictions = melbourne_model.predict(val_X)

In [20]:
val_predictions

array([ 900000.,  696750., 1120000., ...,  240000., 1110000., 1055000.])

In [21]:
print(mean_absolute_error(val_y,val_predictions))

272312.11986227677


In [22]:
def get_mae_for_DTR(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [23]:
import numpy as np

In [24]:
# ans = []
# for max_leaf_nodes in range(2,5000):
#     ans.append(get_mae_for_DTR(max_leaf_nodes, train_X, val_X, train_y, val_y))

In [25]:
# pd.DataFrame({'max_leaf_node':list(range(2,5000)) , 'mae':ans}).to_csv('mln_vs_mae.csv')

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
forest_model = RandomForestRegressor(random_state = 1)
forest_model = forest_model.fit(train_X,train_y)
melb_pred = forest_model.predict(val_X)
print(mean_absolute_error(val_y,melb_pred))

207190.6873773146


In [28]:
def get_mae_for_RFR(n_estimators, train_X, val_X, train_y, val_y):
    model = RandomForestRegressor(n_estimators=n_estimators, random_state=0, n_jobs=-1)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [30]:
ans = []
for n_estimator in range(1,500):
    ans.append(get_mae_for_RFR(n_estimator, train_X, val_X, train_y, val_y))
    print(n_estimator)
    
# pd.DataFrame({'n_estimator':list(range(1,500)) , 'mae':ans}).to_csv('nEst_vs_mae.csv')

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
